server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    include snippets/solo-tailscale.conf;
    return 301 https://$host:443$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;
    include snippets/solo-tailscale.conf;

    ssl_certificate     /etc/ssl/rfid/rasp-tailscale.crt;
    ssl_certificate_key /etc/ssl/rfid/rasp-tailscale.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 8001 default_server;
    listen [::]:8001 default_server;
    client_max_body_size 13m;
    server_name _;
    include snippets/solo-tailscale.conf;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 8443 ssl default_server;
    listen [::]:8443 ssl default_server;
    client_max_body_size 13m;
    server_name _;
    include snippets/solo-tailscale.conf;

    ssl_certificate     /etc/ssl/rfid/rasp-tailscale.crt;
    ssl_certificate_key /etc/ssl/rfid/rasp-tailscale.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://127.0.0.1:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
